# Crop Production Analysis
## 1. Import Libraries and Load Data

In [18]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [19]:
crop = pd.read_csv("D:/Projecst for FTN/Monsoon Impact Analysis on Agriculture Yield/apy.csv")

In [20]:
crop.head()

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0
1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0
2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0
3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0
4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0

## 2. Exploratory Data Analysis (EDA)

In [21]:
crop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 190741 entries, 0 to 190740
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   State_Name     190741 non-null  object
 1   District_Name  190741 non-null  object
 2   Crop_Year      190741 non-null  int64
 3   Season         190741 non-null  object
 4   Crop           190741 non-null  object
 5   Area           190741 non-null  float64
 6   Production     190741 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 10.2+ MB

In [22]:
crop.describe()

           Crop_Year           Area     Production
count  190741.000000  190741.000000  190741.000000
mean     2005.697328    1208.483631    1565.447702
std         4.931001    2080.811909    2896.547890
min      1997.000000       0.100000       0.000000
25%      2002.000000      50.000000      46.000000
50%      2006.000000     277.000000     300.000000
75%      2010.000000    1289.000000    1580.000000
max      2015.000000   11231.000000   17420.000000

In [23]:
crop.isnull().sum()

State_Name       0
District_Name    0
Crop_Year        0
Season           0
Crop             0
Area             0
Production       0
dtype: int64

In [7]:
crop.nunique()

State_Name          33
District_Name      646
Crop_Year           19
Season               6
Crop               124
Area             11108
Production       17643
dtype: int64

## 3. Feature Engineering
We enhance the dataset by calculating the **Yield** ($Yield = \frac{Production}{Area}$) and grouping individual crops into broader categories like Cereals, Pulses, and Fruits for better analysis.

In [24]:
# Calculate Yield
crop.loc[:, 'Yield'] = crop['Production'] / crop['Area']

In [25]:
# yield per crop type
top_yield_crops = crop.groupby('Crop')['Yield'].mean().sort_values(ascending=False)
print(top_yield_crops.head(10))

Crop
Coconut      139.056948
Sugarcane     39.435383
Banana        25.654089
Papaya        23.759814
Grapes        18.228349
Pineapple     13.668379
Tapioca       13.634110
Cashewnut     11.283880
Onion         11.241508
Cabbage       11.172945
Name: Yield, dtype: float64

In [26]:
def get_crop_category(crop):
    crop = crop.lower()
    
    # Cereals 
    if any(x in crop for x in ['rice', 'paddy', 'wheat', 'maize', 'bajra', 'jowar', 'ragi', 'barley', 'millets', 'cereals', 'korra', 'samai', 'varagu']):
        return 'Cereals'
    
    # Pulses
    elif any(x in crop for x in ['pulses', 'gram', 'urad', 'moong', 'masoor', 'arhar', 'tur', 'lentil', 'khesari', 'cowpea', 'moth', 'peas & beans']):
        return 'Pulses'
    
    # Fruits
    elif any(x in crop for x in ['apple', 'banana', 'grapes', 'mango', 'orange', 'papaya', 'pineapple', 'citrus', 'fruit', 'sapota', 'litchi', 'peach', 'pear', 'plums', 'pome']):
        return 'Fruits'
    
    # Vegetables
    elif any(x in crop for x in ['vegetable', 'onion', 'potato', 'tomato', 'brinjal', 'cabbage', 'cauliflower', 'carrot', 'beet root', 'bhindi', 'gourd', 'guard', 'cucumber', 'drum stick', 'radish', 'turnip', 'yam', 'sweet potato', 'tapioca']):
        return 'Vegetables'
    
    # Oilseeds
    elif any(x in crop for x in ['oilseeds', 'groundnut', 'sesamum', 'sunflower', 'soyabean', 'castor', 'mustard', 'linseed', 'safflower', 'niger', 'coconut']):
        return 'Oilseeds'
    
    # Commercial / Plantation / Spices
    elif any(x in crop for x in ['sugarcane', 'tea', 'coffee', 'rubber', 'tobacco', 'cotton', 'kapas', 'jute', 'mesta', 'pepper', 'cardamom', 'ginger', 'garlic', 'turmeric', 'chillies', 'coriander', 'arecanut', 'cashewnut']):
        return 'Commercial'
    
    else:
        return 'Other'


# Apply categorization
crop['Crop_Category'] = crop['Crop'].apply(get_crop_category)

In [27]:
# Check if the new column exists and see the counts
print(crop['Crop_Category'].value_counts())

Crop_Category
Pulses        53818
Cereals       40313
Oilseeds      40242
Commercial    30040
Vegetables    18279
Fruits         4424
Other          3625
Name: count, dtype: int64

In [28]:
crop

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production,Yield,Crop_Category
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0,1.594896,Commercial
1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0,0.500000,Pulses
2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0,3.147059,Cereals
3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0,3.642045,Fruits
4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0,0.229167,Commercial
...,...,...,...,...,...,...,...,...,...
190736,West Bengal,PURULIA,2014,Summer,Maize,325.0,2039.0,6.273846,Cereals
190737,West Bengal,PURULIA,2014,Summer,Rice,306.0,801.0,2.617647,Cereals
190738,West Bengal,PURULIA,2014,Summer,Sesamum,627.0,463.0,0.738437,Oilseeds
190739,West Bengal,PURULIA,2014,Whole Year,Sugarcane,324.0,16250.0,50.154321,Commercial
190740,West Bengal,PURULIA,2014,Winter,Sesamum,175.0,88.0,0.502857,Oilseeds

## 4. Production Trends and Insights

In [29]:
# 1. Correlation Matrix
crop[['Area', 'Production']].corr().round(2)

            Area  Production
Area         1.0         0.6
Production   0.6         1.0

In [30]:
# 2. Which states produce the most volume overall?
top_states = crop.groupby('State_Name')['Production'].sum().nlargest(5)

print("Top 5 States by Total Production:\n")
print(top_states.apply(lambda x: f"{x:,.0f}"))

Top 5 States by Total Production:

State_Name
Uttar Pradesh     39,824,600
Karnataka         26,136,371
Madhya Pradesh    24,897,514
Bihar             24,400,436
Assam             20,200,905
Name: Production, dtype: object

In [31]:
top_states

State_Name
Uttar Pradesh     39824599.70
Karnataka         26136371.34
Madhya Pradesh    24897513.66
Bihar             24400435.66
Assam             20200905.00
Name: Production, dtype: float64

In [32]:
# 3. Which crops take up the most physical land area?
top_area_crops = crop.groupby('Crop')['Area'].sum().nlargest(5)

print("Top 5 Crops by Total Land Area:\n")
print(top_area_crops.apply(lambda x: f"{x:,.0f}"))

Top 5 Crops by Total Land Area:

Crop
Maize                16,725,985
Rice                 15,271,686
Urad                 14,949,025
Arhar/Tur            12,686,416
Rapeseed &Mustard    12,517,953
Name: Area, dtype: object

In [33]:
# 4. How has total production changed over the years?
yearly_production = crop.groupby('Crop_Year')['Production'].sum()

print("Total Production by Year:\n")
print(yearly_production.apply(lambda x: f"{x:,.0f}"))

Total Production by Year:

Crop_Year
1997    11,849,386
1998    14,382,018
1999    16,593,608
2000    16,399,245
2001    16,002,265
2002    18,761,772
2003    20,724,494
2004    16,776,767
2005    16,713,486
2006    16,762,369
2007    16,828,455
2008    17,401,730
2009    16,403,660
2010    17,143,278
2011    17,484,927
2012    16,983,520
2013    17,163,433
2014    13,832,456
2015       388,189
Name: Production, dtype: object

In [17]:
# crop.to_csv('crop_production_cleaned.csv', index=False)
# print("Full cleaned data exported successfully!")